CREATE TABLE IF NOT EXISTS EMPLOYEES(
    EMPLOYEE_ID TEXT,
    EMPLOYEE_NAME TEXT,
    DEPARTMENT TEXT,
    SALARY_REAL REAL
);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT, SALARY_REAL) VALUES
('1', 'JOHN', 'HR', 25000),
('2', 'SARAH', 'FINANCE', 30000),
('3', 'MIKE', 'IT', 28000),
('4', 'LINDA', 'MARKETING', 32000),
('5', 'DAVID', 'IT', 35000);

SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_NAME, SALARY_REAL
FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT = 'IT';

SELECT *
FROM EMPLOYEES
WHERE SALARY_REAL > 30000;

SELECT *
FROM EMPLOYEES
ORDER BY SALARY_REAL DESC;

SELECT *
FROM EMPLOYEES
ORDER BY EMPLOYEE_NAME ASC;

SELECT COUNT(EMPLOYEE_ID) AS Employee_Count
FROM EMPLOYEES;

SELECT AVG(SALARY_REAL) AS Average_Salary
FROM EMPLOYEES;

SELECT SUM(SALARY_REAL) AS Total_Salary
FROM EMPLOYEES;

SELECT MIN(SALARY_REAL) AS Minimum_Salary
FROM EMPLOYEES;

SELECT MAX(SALARY_REAL) AS Maximum_Salary
FROM EMPLOYEES;

SELECT DEPARTMENT, SUM(SALARY_REAL) AS Total_Department_Salary
FROM EMPLOYEES
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, AVG(SALARY_REAL) AS Average_Department_Salary
FROM EMPLOYEES
GROUP BY DEPARTMENT;