CREATE TABLE IF NOT EXISTS HACKER_NEWS(
    ID INTEGER,
    TITLE TEXT,
    AUTHOR TEXT,
    SCORE INTEGER
);

INSERT INTO HACKER_NEWS (ID, TITLE, AUTHOR, SCORE) VALUES
(1, 'Introduction to SQL', 'KARAN', 120),
(2, 'Python Basics', 'JOHN', 95),
(3, 'Machine Learning Guide', 'SARAH', 210),
(4, 'Web Development Trends', 'KARAN', 175),
(5, 'Data Science Tools', 'MIKE', 140);

SELECT * FROM HACKER_NEWS;

SELECT *
FROM HACKER_NEWS
ORDER BY SCORE DESC;

SELECT *
FROM HACKER_NEWS
ORDER BY TITLE ASC;

SELECT *
FROM HACKER_NEWS
WHERE SCORE > 100;

SELECT *
FROM HACKER_NEWS
WHERE AUTHOR = 'KARAN';

SELECT COUNT(*) AS Total_Posts
FROM HACKER_NEWS;

SELECT AVG(SCORE) AS Average_Score
FROM HACKER_NEWS;

SELECT SUM(SCORE) AS Total_Score
FROM HACKER_NEWS;

SELECT MIN(SCORE) AS Lowest_Score
FROM HACKER_NEWS;

SELECT MAX(SCORE) AS Highest_Score
FROM HACKER_NEWS;

SELECT AUTHOR, COUNT(*) AS Total_Posts
FROM HACKER_NEWS
GROUP BY AUTHOR;

SELECT AUTHOR, AVG(SCORE) AS Average_Score
FROM HACKER_NEWS
GROUP BY AUTHOR;

SELECT AUTHOR, SUM(SCORE) AS Total_Score
FROM HACKER_NEWS
GROUP BY AUTHOR
ORDER BY Total_Score DESC;